ALTER TABLE public.country ADD COLUMN "callingCode" INTEGER;

UPDATE public.Country SET "callingCode" = 93 WHERE name = 'Afghanistan';
UPDATE public.Country SET "callingCode" = 355 WHERE name = 'Albania';
UPDATE public.Country SET "callingCode" = 213 WHERE name = 'Argelia';
UPDATE public.Country SET "callingCode" = 1 WHERE name = 'American Samoa';
UPDATE public.Country SET "callingCode" = 376 WHERE name = 'Andorra';
UPDATE public.Country SET "callingCode" = 244 WHERE name = 'Angola';
UPDATE public.Country SET "callingCode" = 1 WHERE name = 'Anguilla';
UPDATE public.Country SET "callingCode" = 672 WHERE name = 'Antarctica';
UPDATE public.Country SET "callingCode" = 1 WHERE name = 'Antigua and Barbuda';
UPDATE public.Country SET "callingCode" = 54 WHERE name = 'Argentina';
UPDATE public.Country SET "callingCode" = 374 WHERE name = 'Armenia';
UPDATE public.Country SET "callingCode" = 297 WHERE name = 'Aruba';
UPDATE public.Country SET "callingCode" = 61 WHERE name = 'Australia';
UPDATE public.Country SET "callingCode" = 43 WHERE name = 'Austria';
UPDATE public.Country SET "callingCode" = 994 WHERE name = 'Azerbaijan';
UPDATE public.Country SET "callingCode" = 1 WHERE name = 'Bahamas';
UPDATE public.Country SET "callingCode" = 973 WHERE name = 'Bahrain';
UPDATE public.Country SET "callingCode" = 880 WHERE name = 'Bangladesh';
UPDATE public.Country SET "callingCode" = 1 WHERE name = 'Barbados';
UPDATE public.Country SET "callingCode" = 375 WHERE name = 'Belarus';
UPDATE public.Country SET "callingCode" = 32 WHERE name = 'Belgium';
UPDATE public.Country SET "callingCode" = 501 WHERE name = 'Belize';
UPDATE public.Country SET "callingCode" = 229 WHERE name = 'Benin';
UPDATE public.Country SET "callingCode" = 1 WHERE name = 'Bermuda';
UPDATE public.Country SET "callingCode" = 975 WHERE name = 'Bhutan';
UPDATE public.Country SET "callingCode" = 591 WHERE name = 'Bolivia';
UPDATE public.Country SET "callingCode" = 387 WHERE name = 'Bosnia and Herzegovina';
UPDATE public.Country SET "callingCode" = 267 WHERE name = 'Botswana';
UPDATE public.Country SET "callingCode" = 55 WHERE name = 'Bouvet Island';
UPDATE public.Country SET "callingCode" = 55 WHERE name = 'Brasil';
UPDATE public.Country SET "callingCode" = 673 WHERE name = 'Brunei Darussalam';
UPDATE public.Country SET "callingCode" = 359 WHERE name = 'Bulgaria';
UPDATE public.Country SET "callingCode" = 226 WHERE name = 'Burkina Faso';
UPDATE public.Country SET "callingCode" = 257 WHERE name = 'Burundi';
UPDATE public.Country SET "callingCode" = 855 WHERE name = 'Cambodia';
UPDATE public.Country SET "callingCode" = 237 WHERE name = 'Cameroon';
UPDATE public.Country SET "callingCode" = 1 WHERE name = 'Canada';
UPDATE public.Country SET "callingCode" = 238 WHERE name = 'Cape Verde';
UPDATE public.Country SET "callingCode" = 1 WHERE name = 'Cayman Islands';
UPDATE public.Country SET "callingCode" = 236 WHERE name = 'Central African Republic';
UPDATE public.Country SET "callingCode" = 235 WHERE name = 'Chad';
UPDATE public.Country SET "callingCode" = 56 WHERE name = 'Chile';
UPDATE public.Country SET "callingCode" = 86 WHERE name = 'China';
UPDATE public.Country SET "callingCode" = 61 WHERE name = 'Christmas Island';
UPDATE public.Country SET "callingCode" = 61 WHERE name = 'Cocos (Keeling) Islands';
UPDATE public.Country SET "callingCode" = 57 WHERE name = 'Colombia';
UPDATE public.Country SET "callingCode" = 269 WHERE name = 'Comoros';
UPDATE public.Country SET "callingCode" = 242 WHERE name = 'Republic of Congo';
UPDATE public.Country SET "callingCode" = 243 WHERE name = 'Democratic Republic of the Congo';
UPDATE public.Country SET "callingCode" = 682 WHERE name = 'Cook Islands';
UPDATE public.Country SET "callingCode" = 506 WHERE name = 'Costa Rica';
UPDATE public.Country SET "callingCode" = 385 WHERE name = 'Croatia (Hrvatska)';
UPDATE public.Country SET "callingCode" = 53 WHERE name = 'Cuba';
UPDATE public.Country SET "callingCode" = 357 WHERE name = 'Cyprus';
UPDATE public.Country SET "callingCode" = 420 WHERE name = 'Czech Republic';
UPDATE public.Country SET "callingCode" = 45 WHERE name = 'Denmark';
UPDATE public.Country SET "callingCode" = 253 WHERE name = 'Djibouti';
UPDATE public.Country SET "callingCode" = 1 WHERE name = 'Dominica';
UPDATE public.Country SET "callingCode" = 1 WHERE name = 'Dominican Republic';
UPDATE public.Country SET "callingCode" = 593 WHERE name = 'Ecuador';
UPDATE public.Country SET "callingCode" = 20 WHERE name = 'Egypt';
UPDATE public.Country SET "callingCode" = 503 WHERE name = 'El Salvador';
UPDATE public.Country SET "callingCode" = 240 WHERE name = 'Equatorial Guinea';
UPDATE public.Country SET "callingCode" = 291 WHERE name = 'Eritrea';
UPDATE public.Country SET "callingCode" = 372 WHERE name = 'Estonia';
UPDATE public.Country SET "callingCode" = 251 WHERE name = 'Ethiopia';
UPDATE public.Country SET "callingCode" = 500 WHERE name = 'Falkland Islands (Malvinas)';
UPDATE public.Country SET "callingCode" = 298 WHERE name = 'Faroe Islands';
UPDATE public.Country SET "callingCode" = 679 WHERE name = 'Fiji';
UPDATE public.Country SET "callingCode" = 358 WHERE name = 'Finland';
UPDATE public.Country SET "callingCode" = 33 WHERE name = 'France';
UPDATE public.Country SET "callingCode" = 594 WHERE name = 'French Guiana';
UPDATE public.Country SET "callingCode" = 689 WHERE name = 'French Polynesia';
UPDATE public.Country SET "callingCode" = 241 WHERE name = 'Gabon';
UPDATE public.Country SET "callingCode" = 220 WHERE name = 'Gambia';
UPDATE public.Country SET "callingCode" = 995 WHERE name = 'Georgia';
UPDATE public.Country SET "callingCode" = 49 WHERE name = 'Germany';
UPDATE public.Country SET "callingCode" = 233 WHERE name = 'Ghana';
UPDATE public.Country SET "callingCode" = 350 WHERE name = 'Gibraltar';
UPDATE public.Country SET "callingCode" = 30 WHERE name = 'Greece';
UPDATE public.Country SET "callingCode" = 299 WHERE name = 'Greenland';
UPDATE public.Country SET "callingCode" = 1 WHERE name = 'Grenada';
UPDATE public.Country SET "callingCode" = 590 WHERE name = 'Guadeloupe';
UPDATE public.Country SET "callingCode" = 1 WHERE name = 'Guam';
UPDATE public.Country SET "callingCode" = 502 WHERE name = 'Guatemala';
UPDATE public.Country SET "callingCode" = 224 WHERE name = 'Guinea';
UPDATE public.Country SET "callingCode" = 245 WHERE name = 'Guinea-Bissau';
UPDATE public.Country SET "callingCode" = 592 WHERE name = 'Guyana';
UPDATE public.Country SET "callingCode" = 509 WHERE name = 'Haiti';
UPDATE public.Country SET "callingCode" = 379 WHERE name = 'Holy See (Vatican City State)';
UPDATE public.Country SET "callingCode" = 504 WHERE name = 'Honduras';
UPDATE public.Country SET "callingCode" = 852 WHERE name = 'Hong Kong';
UPDATE public.Country SET "callingCode" = 36 WHERE name = 'Hungary';
UPDATE public.Country SET "callingCode" = 354 WHERE name = 'Iceland';
UPDATE public.Country SET "callingCode" = 91 WHERE name = 'India';
UPDATE public.Country SET "callingCode" = 62 WHERE name = 'Indonesia';
UPDATE public.Country SET "callingCode" = 98 WHERE name = 'Iran (Islamic Republic of)';
UPDATE public.Country SET "callingCode" = 964 WHERE name = 'Iraq';
UPDATE public.Country SET "callingCode" = 353 WHERE name = 'Ireland';
UPDATE public.Country SET "callingCode" = 972 WHERE name = 'Israel';
UPDATE public.Country SET "callingCode" = 39 WHERE name = 'Italy';
UPDATE public.Country SET "callingCode" = 1 WHERE name = 'Jamaica';
UPDATE public.Country SET "callingCode" = 81 WHERE name = 'Japan';
UPDATE public.Country SET "callingCode" = 962 WHERE name = 'Jordan';
UPDATE public.Country SET "callingCode" = 7 WHERE name = 'Kazakhstan';
UPDATE public.Country SET "callingCode" = 254 WHERE name = 'Kenya';
UPDATE public.Country SET "callingCode" = 686 WHERE name = 'Kiribati';
UPDATE public.Country SET "callingCode" = 82 WHERE name = 'Korea, Republic of';
UPDATE public.Country SET "callingCode" = 850 WHERE name = 'Korea, Democratic Peoples Republic of';
UPDATE public.Country SET "callingCode" = 965 WHERE name = 'Kuwait';
UPDATE public.Country SET "callingCode" = 996 WHERE name = 'Kyrgyzstan';
UPDATE public.Country SET "callingCode" = 856 WHERE name = 'Laos (Lao PDR)';
UPDATE public.Country SET "callingCode" = 371 WHERE name = 'Latvia';
UPDATE public.Country SET "callingCode" = 961 WHERE name = 'Lebanon';
UPDATE public.Country SET "callingCode" = 266 WHERE name = 'Lesotho';
UPDATE public.Country SET "callingCode" = 231 WHERE name = 'Liberia';
UPDATE public.Country SET "callingCode" = 218 WHERE name = 'Libya';
UPDATE public.Country SET "callingCode" = 423 WHERE name = 'Liechtenstein';
UPDATE public.Country SET "callingCode" = 370 WHERE name = 'Lithuania';
UPDATE public.Country SET "callingCode" = 352 WHERE name = 'Luxembourg';
UPDATE public.Country SET "callingCode" = 853 WHERE name = 'Macau';
UPDATE public.Country SET "callingCode" = 389 WHERE name = 'Macedonia, Republic of';
UPDATE public.Country SET "callingCode" = 261 WHERE name = 'Madagascar';
UPDATE public.Country SET "callingCode" = 265 WHERE name = 'Malawi';
UPDATE public.Country SET "callingCode" = 60 WHERE name = 'Malaysia';
UPDATE public.Country SET "callingCode" = 960 WHERE name = 'Maldives';
UPDATE public.Country SET "callingCode" = 223 WHERE name = 'Mali';
UPDATE public.Country SET "callingCode" = 356 WHERE name = 'Malta';
UPDATE public.Country SET "callingCode" = 692 WHERE name = 'Marshall Islands';
UPDATE public.Country SET "callingCode" = 596 WHERE name = 'Martinique';
UPDATE public.Country SET "callingCode" = 222 WHERE name = 'Mauritania';
UPDATE public.Country SET "callingCode" = 230 WHERE name = 'Mauritius';
UPDATE public.Country SET "callingCode" = 262 WHERE name = 'Mayotte';
UPDATE public.Country SET "callingCode" = 52 WHERE name = 'Mexico';
UPDATE public.Country SET "callingCode" = 691 WHERE name = 'Micronesia, Federated States of';
UPDATE public.Country SET "callingCode" = 373 WHERE name = 'Moldova, Republic of';
UPDATE public.Country SET "callingCode" = 377 WHERE name = 'Monaco';
UPDATE public.Country SET "callingCode" = 976 WHERE name = 'Mongolia';
UPDATE public.Country SET "callingCode" = 382 WHERE name = 'Montenegro';
UPDATE public.Country SET "callingCode" = 1 WHERE name = 'Montserrat';
UPDATE public.Country SET "callingCode" = 212 WHERE name = 'Morocco';
UPDATE public.Country SET "callingCode" = 258 WHERE name = 'Mozambique';
UPDATE public.Country SET "callingCode" = 95 WHERE name = 'Myanmar';
UPDATE public.Country SET "callingCode" = 264 WHERE name = 'Namibia';
UPDATE public.Country SET "callingCode" = 674 WHERE name = 'Nauru';
UPDATE public.Country SET "callingCode" = 977 WHERE name = 'Nepal';
UPDATE public.Country SET "callingCode" = 31 WHERE name = 'Netherlands';
UPDATE public.Country SET "callingCode" = 599 WHERE name = 'Netherlands Antilles';
UPDATE public.Country SET "callingCode" = 687 WHERE name = 'New Caledonia';
UPDATE public.Country SET "callingCode" = 64 WHERE name = 'New Zealand';
UPDATE public.Country SET "callingCode" = 505 WHERE name = 'Nicaragua';
UPDATE public.Country SET "callingCode" = 227 WHERE name = 'Niger';
UPDATE public.Country SET "callingCode" = 234 WHERE name = 'Nigeria';
UPDATE public.Country SET "callingCode" = 683 WHERE name = 'Niue';
UPDATE public.Country SET "callingCode" = 672 WHERE name = 'Norfolk Island';
UPDATE public.Country SET "callingCode" = 1 WHERE name = 'Northern Mariana Islands';
UPDATE public.Country SET "callingCode" = 47 WHERE name = 'Norway';
UPDATE public.Country SET "callingCode" = 968 WHERE name = 'Oman';
UPDATE public.Country SET "callingCode" = 92 WHERE name = 'Pakistan';
UPDATE public.Country SET "callingCode" = 680 WHERE name = 'Palau';
UPDATE public.Country SET "callingCode" = 970 WHERE name = 'Palestine';
UPDATE public.Country SET "callingCode" = 507 WHERE name = 'Panama';
UPDATE public.Country SET "callingCode" = 675 WHERE name = 'Papua New Guinea';
UPDATE public.Country SET "callingCode" = 595 WHERE name = 'Paraguay';
UPDATE public.Country SET "callingCode" = 51 WHERE name = 'Peru';
UPDATE public.Country SET "callingCode" = 63 WHERE name = 'Philippines';
UPDATE public.Country SET "callingCode" = 870 WHERE name = 'Pitcairn';
UPDATE public.Country SET "callingCode" = 48 WHERE name = 'Poland';
UPDATE public.Country SET "callingCode" = 351 WHERE name = 'Portugal';
UPDATE public.Country SET "callingCode" = 1 WHERE name = 'Puerto Rico';
UPDATE public.Country SET "callingCode" = 974 WHERE name = 'Qatar';
UPDATE public.Country SET "callingCode" = 262 WHERE name = 'Réunion and Mayotte';
UPDATE public.Country SET "callingCode" = 40 WHERE name = 'Romania';
UPDATE public.Country SET "callingCode" = 7 WHERE name = 'Russian Federation';
UPDATE public.Country SET "callingCode" = 250 WHERE name = 'Rwanda';
UPDATE public.Country SET "callingCode" = 290 WHERE name = 'Saint Helena and also Tristan Da Cunha';
UPDATE public.Country SET "callingCode" = 1 WHERE name = 'Saint Kitts and Nevis';
UPDATE public.Country SET "callingCode" = 1 WHERE name = 'Saint Lucia';
UPDATE public.Country SET "callingCode" = 508 WHERE name = 'Saint Pierre and Miquelon';
UPDATE public.Country SET "callingCode" = 1 WHERE name = 'Saint Vincent and the Grenadines';
UPDATE public.Country SET "callingCode" = 685 WHERE name = 'Samoa';
UPDATE public.Country SET "callingCode" = 378 WHERE name = 'San Marino';
UPDATE public.Country SET "callingCode" = 239 WHERE name = 'São Tomé and Principe';
UPDATE public.Country SET "callingCode" = 966 WHERE name = 'Saudi Arabia';
UPDATE public.Country SET "callingCode" = 221 WHERE name = 'Senegal';
UPDATE public.Country SET "callingCode" = 381 WHERE name = 'Serbia';
UPDATE public.Country SET "callingCode" = 248 WHERE name = 'Seychelles';
UPDATE public.Country SET "callingCode" = 232 WHERE name = 'Sierra Leone';
UPDATE public.Country SET "callingCode" = 65 WHERE name = 'Singapore';
UPDATE public.Country SET "callingCode" = 421 WHERE name = 'Slovakia';
UPDATE public.Country SET "callingCode" = 386 WHERE name = 'Slovenia';
UPDATE public.Country SET "callingCode" = 677 WHERE name = 'Solomon Islands';
UPDATE public.Country SET "callingCode" = 252 WHERE name = 'Somalia';
UPDATE public.Country SET "callingCode" = 27 WHERE name = 'South Africa';
UPDATE public.Country SET "callingCode" = 34 WHERE name = 'Spain';
UPDATE public.Country SET "callingCode" = 94 WHERE name = 'Sri Lanka';
UPDATE public.Country SET "callingCode" = 249 WHERE name = 'South Sudan';
UPDATE public.Country SET "callingCode" = 597 WHERE name = 'Suriname';
UPDATE public.Country SET "callingCode" = 47 WHERE name = 'Svalbard and Jan Mayen Islands';
UPDATE public.Country SET "callingCode" = 268 WHERE name = 'Swaziland';
UPDATE public.Country SET "callingCode" = 46 WHERE name = 'Sweden';
UPDATE public.Country SET "callingCode" = 41 WHERE name = 'Switzerland';
UPDATE public.Country SET "callingCode" = 963 WHERE name = 'Syrian Arab Republic';
UPDATE public.Country SET "callingCode" = 886 WHERE name = 'Taiwan';
UPDATE public.Country SET "callingCode" = 992 WHERE name = 'Tajikistan';
UPDATE public.Country SET "callingCode" = 255 WHERE name = 'Tanzania, United Republic of';
UPDATE public.Country SET "callingCode" = 66 WHERE name = 'Thailand';
UPDATE public.Country SET "callingCode" = 670 WHERE name = 'Timor-Leste';
UPDATE public.Country SET "callingCode" = 228 WHERE name = 'Togo';
UPDATE public.Country SET "callingCode" = 690 WHERE name = 'Tokelau';
UPDATE public.Country SET "callingCode" = 676 WHERE name = 'Tonga';
UPDATE public.Country SET "callingCode" = 1 WHERE name = 'Trinidad and Tobago';
UPDATE public.Country SET "callingCode" = 216 WHERE name = 'Tunisia';
UPDATE public.Country SET "callingCode" = 90 WHERE name = 'Turkey';
UPDATE public.Country SET "callingCode" = 993 WHERE name = 'Turkmenistan';
UPDATE public.Country SET "callingCode" = 1 WHERE name = 'Turks and Caicos Islands';
UPDATE public.Country SET "callingCode" = 688 WHERE name = 'Tuvalu';
UPDATE public.Country SET "callingCode" = 256 WHERE name = 'Uganda';
UPDATE public.Country SET "callingCode" = 380 WHERE name = 'Ukraine';
UPDATE public.Country SET "callingCode" = 971 WHERE name = 'United Arab Emirates';
UPDATE public.Country SET "callingCode" = 44 WHERE name = 'United Kingdom';
UPDATE public.Country SET "callingCode" = 1 WHERE name = 'United States';
UPDATE public.Country SET "callingCode" = 598 WHERE name = 'Uruguay';
UPDATE public.Country SET "callingCode" = 998 WHERE name = 'Uzbekistan';
UPDATE public.Country SET "callingCode" = 678 WHERE name = 'Vanuatu';
UPDATE public.Country SET "callingCode" = 58 WHERE name = 'Venezuela';
UPDATE public.Country SET "callingCode" = 84 WHERE name = 'Vietnam';
UPDATE public.Country SET "callingCode" = 1 WHERE name = 'Virgin Islands (British)';
UPDATE public.Country SET "callingCode" = 1 WHERE name = 'Virgin Islands (U.S.)';
UPDATE public.Country SET "callingCode" = 681 WHERE name = 'Wallis and Futuna Islands';
UPDATE public.Country SET "callingCode" = 967 WHERE name = 'Yemen';
UPDATE public.Country SET "callingCode" = 260 WHERE name = 'Zambia';
UPDATE public.Country SET "callingCode" = 263 WHERE name = 'Zimbabwe';
