version: "3"
services:
  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - ../db:/docker-entrypoint-initdb.d/db
      - ../db/create_database.sh:/docker-entrypoint-initdb.d/create_database.sh
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "8081:80"
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@atixlabs.com
      - PGADMIN_DEFAULT_PASSWORD=test

#   circles-of-angels-api-v2:
#     container_name: circles-of-angels-api-v2
#     restart: always
#     depends_on:
#       - db
#     build: ../.
#     ports:
#       - "3001:3001"
#     networks:
#       - app-network
#     command: "npm start"

#   proxy:
#     image: nginx:alpine
#     container_name: web-proxy
#     restart: unless-stopped
#     volumes:
#       - ../proxy.conf:/etc/nginx/conf.d/default.conf
#     ports:
#       - 80:80
#     depends_on:
#       - circles-of-angels-api-v2
#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge