version: '3'
services:
  db:
    image: postgres:latest
    container_name: db
    ports:
      - '5432:5432'
    volumes:
      - ../db/scripts/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - '8081:80'
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@atixlabs.com
      - PGADMIN_DEFAULT_PASSWORD=test
